"""add application status enum

Revision ID: c94769d0e27a
Revises: 
Create Date: 2026-09-04 13:31:50.612630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94769d0e27a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    application_status_enum = sa.Enum(
        'APPLIED',
        'ACTIVE',
        'REJECTED',
        'SELECTED',
        name='applicationstatus'
    )
    application_status_enum.create(op.get_bind())

    op.alter_column(
        'applications',
        'status',
        existing_type=sa.VARCHAR(length=30),
        type_=application_status_enum,
        postgresql_using="status::applicationstatus",
        existing_nullable=False
    )
    op.drop_constraint(
        op.f('unique_user_company'),
        'applications',
        type_='unique'
    )
    op.create_unique_constraint(
        'uq_application_user_company',
        'applications',
        ['user_id', 'company_id']
    )
    op.alter_column(
        'users',
        'email',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False
    )
    op.alter_column(
        'users',
        'role',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=100),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::character varying")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint('uq_application_user_company', 'applications', type_='unique')
    op.create_unique_constraint(op.f('unique_user_company'), 'applications', ['user_id', 'company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('APPLIED', 'ACTIVE', 'REJECTED', 'SELECTED', name='applicationstatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
